/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nazwaprojektu;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static nazwaprojektu.Restauracja.klienci;
import static nazwaprojektu.Restauracja.ekipa;
import static nazwaprojektu.NazwaProjektu.restauracja;
import static nazwaprojektu.NazwaProjektu.Xclick;
import static nazwaprojektu.NazwaProjektu.Yclick;
import static nazwaprojektu.NazwaProjektu.output;
/**
 *
 * @author Kubik
 */
public class Okno extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form Okno
     */
    private String info;
    
    public Okno() {
        addMouseListener(this);
        initComponents();
        usunDostawce.setVisible(false);
        usunKlienta.setVisible(false);
        noweZamowienie.setVisible(false);
        zawrocDostawce.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelKontrolny = new javax.swing.JPanel();
        jOpcjeDodawania = new javax.swing.JPanel();
        jOkazjonalny = new javax.swing.JButton();
        jStały = new javax.swing.JButton();
        jFirmowy = new javax.swing.JButton();
        jDostawca = new javax.swing.JButton();
        jPosiłek = new javax.swing.JButton();
        jKO_label = new javax.swing.JLabel();
        jKS_label = new javax.swing.JLabel();
        jKF_label = new javax.swing.JLabel();
        jD_label = new javax.swing.JLabel();
        jP_label = new javax.swing.JLabel();
        jOknoInfo = new PanelInfo();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputArea = new javax.swing.JTextArea();
        usunDostawce = new javax.swing.JButton();
        noweZamowienie = new javax.swing.JButton();
        zawrocDostawce = new javax.swing.JButton();
        usunKlienta = new javax.swing.JButton();
        jTimeLabel = new javax.swing.JLabel();
        odczytDanych = new javax.swing.JButton();
        zapisDanych = new javax.swing.JButton();
        jPanelMapy = new Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Symulator5000");
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 660));

        jPanelKontrolny.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeBorderColor"));
        jPanelKontrolny.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PANEL KONTROLNY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanelKontrolny.setName("panel_kontrolny"); // NOI18N
        jPanelKontrolny.setPreferredSize(new java.awt.Dimension(300, 660));
        jPanelKontrolny.setLayout(new java.awt.BorderLayout());

        jOpcjeDodawania.setBackground(new java.awt.Color(204, 204, 204));
        jOpcjeDodawania.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dodawanie obiektów", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        jOpcjeDodawania.setPreferredSize(new java.awt.Dimension(288, 280));

        jOkazjonalny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dodaj_okazjonalnego.png"))); // NOI18N
        jOkazjonalny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkazjonalnyActionPerformed(evt);
            }
        });

        jStały.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dodaj_stalego.png"))); // NOI18N
        jStały.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStałyActionPerformed(evt);
            }
        });

        jFirmowy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dodaj_firmowego.png"))); // NOI18N
        jFirmowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirmowyActionPerformed(evt);
            }
        });

        jDostawca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dodaj_dostawce.png"))); // NOI18N
        jDostawca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDostawcaActionPerformed(evt);
            }
        });

        jPosiłek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dodaj_posilek.png"))); // NOI18N
        jPosiłek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPosiłekActionPerformed(evt);
            }
        });

        jKO_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jKO_label.setText("Nowy klient okazjonalny");

        jKS_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jKS_label.setText("Nowy klient stały");

        jKF_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jKF_label.setText("Nowy klient firmowy");

        jD_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jD_label.setText("Nowy dostawca");

        jP_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jP_label.setText("Nowy posiłek");

        javax.swing.GroupLayout jOpcjeDodawaniaLayout = new javax.swing.GroupLayout(jOpcjeDodawania);
        jOpcjeDodawania.setLayout(jOpcjeDodawaniaLayout);
        jOpcjeDodawaniaLayout.setHorizontalGroup(
            jOpcjeDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcjeDodawaniaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jOpcjeDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jOpcjeDodawaniaLayout.createSequentialGroup()
                        .addComponent(jOkazjonalny, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jKO_label))
                    .addGroup(jOpcjeDodawaniaLayout.createSequentialGroup()
                        .addComponent(jStały, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jKS_label))
                    .addGroup(jOpcjeDodawaniaLayout.createSequentialGroup()
                        .addComponent(jFirmowy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jKF_label))
                    .addGroup(jOpcjeDodawaniaLayout.createSequentialGroup()
                        .addComponent(jDostawca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jD_label))
                    .addGroup(jOpcjeDodawaniaLayout.createSequentialGroup()
                        .addComponent(jPosiłek, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jP_label)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jOpcjeDodawaniaLayout.setVerticalGroup(
            jOpcjeDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcjeDodawaniaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jOpcjeDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jOkazjonalny, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jKO_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jOpcjeDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jStały, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jKS_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jOpcjeDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFirmowy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jKF_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jOpcjeDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDostawca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jD_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jOpcjeDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPosiłek, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_label))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelKontrolny.add(jOpcjeDodawania, java.awt.BorderLayout.PAGE_START);

        jOknoInfo.setBackground(new java.awt.Color(204, 204, 204));
        jOknoInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Okno informacyjne", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        jOknoInfo.setPreferredSize(new java.awt.Dimension(288, 320));
        jOknoInfo.setLayout(null);

        OutputArea.setEditable(false);
        OutputArea.setBackground(new java.awt.Color(204, 204, 204));
        OutputArea.setColumns(20);
        OutputArea.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        OutputArea.setRows(5);
        jScrollPane1.setViewportView(OutputArea);

        jOknoInfo.add(jScrollPane1);
        jScrollPane1.setBounds(12, 19, 250, 200);

        usunDostawce.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        usunDostawce.setText("Usuń Dostawcę");
        usunDostawce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunDostawceActionPerformed(evt);
            }
        });
        jOknoInfo.add(usunDostawce);
        usunDostawce.setBounds(10, 220, 120, 40);

        noweZamowienie.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        noweZamowienie.setText("Złóż Zamówienie");
        noweZamowienie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noweZamowienieActionPerformed(evt);
            }
        });
        jOknoInfo.add(noweZamowienie);
        noweZamowienie.setBounds(140, 270, 120, 40);

        zawrocDostawce.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        zawrocDostawce.setText("Zawróć Dostawcę");
        zawrocDostawce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zawrocDostawceActionPerformed(evt);
            }
        });
        jOknoInfo.add(zawrocDostawce);
        zawrocDostawce.setBounds(140, 220, 120, 40);

        usunKlienta.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        usunKlienta.setText("Usuń Klienta");
        usunKlienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunKlientaActionPerformed(evt);
            }
        });
        jOknoInfo.add(usunKlienta);
        usunKlienta.setBounds(10, 270, 120, 40);

        jPanelKontrolny.add(jOknoInfo, java.awt.BorderLayout.PAGE_END);

        jTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTimeLabel.setText("Ładowanie...");
        jTimeLabel.setToolTipText("");
        jTimeLabel.setPreferredSize(new java.awt.Dimension(35, 14));
        jPanelKontrolny.add(jTimeLabel, java.awt.BorderLayout.CENTER);

        odczytDanych.setText("Odczyt");
        odczytDanych.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odczytDanychActionPerformed(evt);
            }
        });
        jPanelKontrolny.add(odczytDanych, java.awt.BorderLayout.LINE_START);

        zapisDanych.setText("Zapis");
        zapisDanych.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapisDanychActionPerformed(evt);
            }
        });
        jPanelKontrolny.add(zapisDanych, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanelKontrolny, java.awt.BorderLayout.EAST);

        jPanelMapy.setBorder(new javax.swing.border.MatteBorder(null));
        jPanelMapy.setAlignmentX(0.0F);
        jPanelMapy.setAlignmentY(0.0F);
        jPanelMapy.setName("panel_mapy"); // NOI18N
        jPanelMapy.setPreferredSize(new java.awt.Dimension(1200, 665));

        javax.swing.GroupLayout jPanelMapyLayout = new javax.swing.GroupLayout(jPanelMapy);
        jPanelMapy.setLayout(jPanelMapyLayout);
        jPanelMapyLayout.setHorizontalGroup(
            jPanelMapyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1198, Short.MAX_VALUE)
        );
        jPanelMapyLayout.setVerticalGroup(
            jPanelMapyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelMapy, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOkazjonalnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkazjonalnyActionPerformed
        info=null;
        info=restauracja.dodajKlientaOka();
        if(info.charAt(0) == 'b'){
            OutputArea.setText(info);
        }
        else{
            OutputArea.setText("Klient dodany pomyślnie!\n"+klienci.get(info).outDane());
        }
    }//GEN-LAST:event_jOkazjonalnyActionPerformed

    private void jStałyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStałyActionPerformed
        info=null;
        info=restauracja.dodajKlientaSta();
        if(info.charAt(0) == 'b'){
            OutputArea.setText(info);
        }
        else{
            OutputArea.setText("Klient dodany pomyślnie!\n"+klienci.get(info).outDane());
        }
        
    }//GEN-LAST:event_jStałyActionPerformed

    private void jFirmowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirmowyActionPerformed
        info=null;
        info=restauracja.dodajKlientaFir();
        if(info.charAt(0) == 'b'){
            OutputArea.setText(info);
        }
        else{
            OutputArea.setText("Klient dodany pomyślnie!\n"+klienci.get(info).outDane());
        }
    }//GEN-LAST:event_jFirmowyActionPerformed

    private void jDostawcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDostawcaActionPerformed
        info=null;
        info=restauracja.dodajDostawce();
        if(info.charAt(0) == 'R'){
            OutputArea.setText(info);
        }
        else{
            OutputArea.setText("Dostawca dodany pomyślnie!\n"+ekipa.get(info).outDane());
        }
    }//GEN-LAST:event_jDostawcaActionPerformed

    private void jPosiłekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPosiłekActionPerformed
        info=null;
        info=restauracja.dodajPosilek();
        if(info.charAt(0) == 'm'){
            OutputArea.setText(info);
        }
        else{
            OutputArea.setText("Posiłek dodany pomyślnie!\n");
        }
    }//GEN-LAST:event_jPosiłekActionPerformed

    private void usunDostawceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunDostawceActionPerformed
        info=null;
        info=restauracja.usunDostawce(output);
        OutputArea.setText(info);
        usunDostawce.setVisible(false);
        zawrocDostawce.setVisible(false);
    }//GEN-LAST:event_usunDostawceActionPerformed

    private void usunKlientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunKlientaActionPerformed
        info=null;
        info=restauracja.usunKlienta(output);
        OutputArea.setText(info);
        usunKlienta.setVisible(false);
        noweZamowienie.setVisible(false);
    }//GEN-LAST:event_usunKlientaActionPerformed

    private void zawrocDostawceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zawrocDostawceActionPerformed
        ekipa.get(output).setNaglyPowrot(true);
    }//GEN-LAST:event_zawrocDostawceActionPerformed

    private void noweZamowienieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noweZamowienieActionPerformed
        klienci.get(output).zlozZamowienie();
    }//GEN-LAST:event_noweZamowienieActionPerformed

    private void odczytDanychActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odczytDanychActionPerformed
        try {
            restauracja.wczytajDane();
        } catch (IOException ex) {
            System.err.println("BLAD PLIKU ODCZYTU");
        } catch (ClassNotFoundException ex) {
            System.err.println("BLAD KLASY");
        }
    }//GEN-LAST:event_odczytDanychActionPerformed

    private void zapisDanychActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapisDanychActionPerformed
        try {
            restauracja.zapiszDane();
        } catch (IOException ex) {
            ex.printStackTrace();
            System.err.println("BLAD PLIKU ZAPISU");
        }
    }//GEN-LAST:event_zapisDanychActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea OutputArea;
    private javax.swing.JLabel jD_label;
    private javax.swing.JButton jDostawca;
    private javax.swing.JButton jFirmowy;
    private javax.swing.JLabel jKF_label;
    private javax.swing.JLabel jKO_label;
    private javax.swing.JLabel jKS_label;
    private javax.swing.JButton jOkazjonalny;
    private javax.swing.JPanel jOknoInfo;
    private javax.swing.JPanel jOpcjeDodawania;
    private javax.swing.JLabel jP_label;
    private javax.swing.JPanel jPanelKontrolny;
    private javax.swing.JPanel jPanelMapy;
    private javax.swing.JButton jPosiłek;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jStały;
    public static javax.swing.JLabel jTimeLabel;
    private javax.swing.JButton noweZamowienie;
    private javax.swing.JButton odczytDanych;
    private javax.swing.JButton usunDostawce;
    private javax.swing.JButton usunKlienta;
    private javax.swing.JButton zapisDanych;
    private javax.swing.JButton zawrocDostawce;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {

    }

    @Override
    public void mousePressed(MouseEvent e) {
        Xclick = e.getX();
        Yclick = e.getY()-26;
        output=restauracja.getGenerator().zwrocKlucz(Xclick, Yclick);
        if(output.contains(" ")){
            noweZamowienie.setVisible(true);
            usunKlienta.setVisible(true);
            usunDostawce.setVisible(false);
            zawrocDostawce.setVisible(false);
        }
        else if(output.length() == 11){
            zawrocDostawce.setVisible(true);
            usunDostawce.setVisible(true);
            usunKlienta.setVisible(false);
            noweZamowienie.setVisible(false);
        }
        else{
            usunDostawce.setVisible(false);
            usunKlienta.setVisible(false);
            noweZamowienie.setVisible(false);
            zawrocDostawce.setVisible(false);
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {

    }

    @Override
    public void mouseExited(MouseEvent e) {

    }
}
