/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nazwaprojektu;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import static nazwaprojektu.Restauracja.klienci;
import static nazwaprojektu.Restauracja.mapa;
import static nazwaprojektu.Restauracja.ekipa;
import static nazwaprojektu.Okno.jTimeLabel;
import static nazwaprojektu.Okno.OutputArea;
import static nazwaprojektu.NazwaProjektu.output;
import static nazwaprojektu.NazwaProjektu.lockKlienci;
import static nazwaprojektu.NazwaProjektu.lockEkipa;


/**
 *
 * @author Kubik
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form PanelMapy
     */
    private BufferedImage ikona;
    private int pozX;
    private int pozY;
    private int nrDomu;
    private Set<String> keys;
    private String kierunekJazdy;
    private Format data = new SimpleDateFormat("HH:mm:ss");
    
    public Panel() {
        initComponents();
    }
    
    @Override
	public void paintComponent(Graphics g) {
		Graphics2D g2d = (Graphics2D) g;
                jTimeLabel.setText(data.format(new Date()));
                g2d.drawImage(mapa,0,0,this);
                lockKlienci.lock();
                try{
                    if(klienci.containsKey(output)) OutputArea.setText(klienci.get(output).outDane());
                    keys=klienci.keySet();
                    for (String key : keys) {
                        ikona=klienci.get(key).getIkona();
                        pozX=klienci.get(key).getPozycjaX()-30;
                        pozY=klienci.get(key).getPozycjaY();
                        nrDomu=klienci.get(key).getNrDomu();
                        if(nrDomu%2 == 0)   pozY = pozY-100;
                        else    pozY = pozY+40;
                        g2d.drawImage(ikona,pozX,pozY,this);
                    }
                } finally{
                    lockKlienci.unlock();
                }
                lockEkipa.lock();
                try{
                    if(ekipa.containsKey(output)) OutputArea.setText(ekipa.get(output).outDane());
                    keys=ekipa.keySet();
                    for (String key : keys) {
                        if(!ekipa.get(key).iswTrasie()) continue;
                        ikona=ekipa.get(key).getIkona();
                        pozX=ekipa.get(key).getPozycjaX();
                        pozY=ekipa.get(key).getPozycjaY();
                        kierunekJazdy=ekipa.get(key).getKierunekJazdy();
                        if(kierunekJazdy.equals("prawo")){
                            pozX=pozX-60;
                        }
                        else if(kierunekJazdy.equals("lewo")){
                            pozY=pozY-40;
                        }
                        else if(kierunekJazdy.equals("gora")){
                            pozX=pozX+10;
                        }
                        else if(kierunekJazdy.equals("dol")){
                            pozX=pozX-50;
                            pozY=pozY-60;
                        }
                        g2d.drawImage(ikona,pozX,pozY,this);
                    }
                } finally{
                    lockEkipa.unlock();
                }
                if(output.equals("")) OutputArea.setText(output);
                repaint();
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
